export const Actions = {
  GET_OFFERS: 'GET_OFFERS',
  GET_OFFER: 'GET_OFFER',
  GET_OFFERS_NEARBY: 'GET_OFFERS_NEARBY',
  GET_FAVORITES_OFFERS: 'GET_FAVORITES_OFFERS',
  CHANGE_CITY: 'CHANGE_CITY',
  CHECK_AUTH: 'CHECK_AUTH',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  GET_COMMENTS: 'GET_COMMENTS',
  POST_COMMENT: 'POST_COMMENT',
};
